name: first workflow

on: 
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - name: print welcome message
        run : echo " welcome to our first github actions workflow" 
      
      - name: list repository files before checkout
        run: ls -la

      - name: checkout repository
        uses: actions/checkout@v6.0.2

      - name: list repository files after checkout
        run: ls -la
